name: Cypress CI

on:
  push:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        suite: [smoke, regression]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          install: true
          browser: electron
          spec: cypress/e2e/${{ matrix.suite }}/**/*
          config-file: cypress.config.js
          reporter: mochawesome
          reporter-options: reportDir=reports/${{ matrix.suite }},overwrite=false,html=false,json=true

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: report-${{ matrix.suite }}
          path: reports/${{ matrix.suite }}