name: Cypress CI

on:
  push:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        suite: [smoke, regression]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Install Cypress binary
        run: npx cypress install

      - name: Verify Cypress
        run: npx cypress verify

      - name: Run Cypress tests with Mochawesome
        run: |
          npx cypress run \
          --spec "cypress/e2e/${{ matrix.suite }}/**/*" \
          --reporter mochawesome \
          --reporter-options reportDir=reports/${{ matrix.suite }},overwrite=false,html=false,json=true

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: report-${{ matrix.suite }}
          path: reports/${{ matrix.suite }}